### ISSUE TITLE
Issue getting syntax highlight json file to work

### ISSUE THREAD

**Issue by mrfearless** [Daniel0110000/DeepCodeStudio#2]
Hi, I tried out the DeepCodeStudio editor, but I am having a problem trying to get it to work properly. 

Couldnt find any json files included with the release, so copied the example from the readme to a asmX86.json file.

Any time i browsed to the file location and selected it to open, it would show the filename below the text input box, but nothing else showed in the syntax highlighter options section.

Does it look for specific filesnames in specific folders automatically on launch, or is there a way to successfully add the json file? 

Also do you have json files that you can provide to start with - even the example one would be handy, and advice on where to place the file. 

Thanks.

**Comment by Daniel0110000** [comment]
Hi, during the week I will be updating the README and providing more detailed instructions on how to correctly configure it for proper use.
